export const images = {
  logo:          require('./images/logo.png'),
  logoTransparent: require('./images/logo-transparent.png'),
  raceLogoFull:  require('./images/race-logo-full.png'),
  splashContent: require('./images/splash-content.png'),
  splashBg:        require('./images/splash-bg.png'),
  splashExtended:  require('./images/splash-extended.png'),
  splashHero:    require('./images/splash-hero-clean.png'),
  splashHeroAlt: require('./images/splash-hero.jpeg'),
  splashScreen:  require('./images/splash-screen.jpeg'),
  splashArt:     require('./images/splash-art.png'),
  splashHeader:  require('./images/splash-header.png'),
  splashTruck:   require('./images/splash-truck.png'),
  splashBackground: require('./images/golden-sunrise-tow-truck-highway.png'),
  authSignupTechnician: require('./images/auth-signup-technician.jpg'),
  authSigninSunset: require('./images/auth-signin-sunset.jpg'),
  onboarding1:   require('./images/onboarding-1.png'),
  onboarding2:   require('./images/onboarding-2.png'),
  onboarding3:   require('./images/onboarding-3.png'),
  onboarding4:   require('./images/onboarding-4.png'),
  homeHeroTruck: require('./images/home-hero-truck.png'),
  homeHeroRoadTruck: require('./images/home-hero-road-truck.jpg'),
  popularTowingCardTruck: require('./images/popular-towing-card-truck.png'),
  popularTyreCardGraphic: require('./images/popular-tyre-card-graphic.png'),
  homePopularTowing: require('./images/home-popular-towing.png'),
  homePopularRoadside: require('./images/home-popular-roadside.png'),
  homePopularDriver: require('./images/home-popular-driver.png'),
  homePopularRepair: require('./images/home-popular-repair.png'),
  homePopularRecovery: require('./images/home-popular-recovery.png'),
  moreServicesBanner: require('./images/more-services/expanding-banner.png'),
  towingHeroBanner: require('./images/towing-hero-banner.png'),
  roadsideHeroBanner: require('./images/roadside-hero-banner.png'),
  driverHeroBanner: require('./images/driver-hero-banner.png'),
  serviceTowingCard: require('./images/services/service-towing-card.png'),
  serviceDriverCard: require('./images/services/service-driver-card.png'),
  serviceRoadsideCard: require('./images/services/service-roadside-card.png'),
  serviceMoreCard: require('./images/services/service-more-card.png'),
  booking: {
    vehicleHatchback: require('./images/booking/vehicle-hatchback.png'),
    vehicleSedan: require('./images/booking/vehicle-sedan.png'),
    vehicleSuv: require('./images/booking/vehicle-suv.png'),
    vehicleBike: require('./images/booking/vehicle-bike.png'),
    towingFlatbed: require('./images/booking/towing-flatbed.png'),
    towingWheelLift: require('./images/booking/towing-wheel-lift.png'),
    driverParttime: require('./images/booking/driver/icon-parttime.png'),
    driverFulltime: require('./images/booking/driver/icon-fulltime.png'),
    driverOutstation: require('./images/booking/driver/icon-outstation.png'),
    driverNight: require('./images/booking/driver/icon-night.png'),
    driverPickupMap: require('./images/booking/driver/pickup-map.png'),
    driverRamesh: require('./images/booking/driver/driver-ramesh.png'),
    roadsideTyre: require('./images/booking/roadside/service-tyre.png'),
    roadsideBattery: require('./images/booking/roadside/service-battery.png'),
    roadsideFuel: require('./images/booking/roadside/service-fuel.png'),
    roadsideRepairs: require('./images/booking/roadside/service-repairs.png'),
    roadsideLocationMap: require('./images/booking/roadside/location-map.png'),
    roadsideMechanic: require('./images/booking/roadside/mechanic-ramesh.png'),
    roadsideHelpTruck: require('./images/booking/roadside/help-truck.png'),
  },
  icons: {
    future:     require('./images/icons/future.png'),
    motorcycle: require('./images/icons/motorcycle.png'),
    roadside:   require('./images/icons/roadside.png'),
    towing:     require('./images/icons/towing.png'),
    truck:      require('./images/icons/truck.png'),
  },
} as const;

export const categoryIcons = {
  towing: images.icons.towing,
  roadside: images.icons.roadside,
  driver: images.icons.truck,
  future: images.icons.future,
} as const;

export type ImageKeys = keyof typeof images;